select SPACEID,PERMTYPE,PERMUSERNAME FROM SPACEPERMISSIONS WHERE PERMUSERNAME IS NOT NULL GROUP BY SPACEID,PERMTYPE,PERMUSERNAME ORDER BY SPACEID DESC


SELECT SPACEID, SPACEKEY FROM SPACES WHERE SPACEID IN (select DISTINCT(SPACEID) FROM SPACEPERMISSIONS WHERE PERMUSERNAME IS NOT NULL GROUP BY SPACEID,PERMTYPE,PERMUSERNAME) AND (SPACES.SPACETYPE = 'global')ORDER BY SPACEID DESC



select user_key,username from user_mapping where user_key IN (select PERMUSERNAME from SPACEPERMISSIONS WHERE PERMUSERNAME IS NOT NULL)ORDER BY user_key ASC