// SQL Query to Identify Project Mappings to GIT Repositories of GIT Lab

SELECT GRP.ROOT, GRP.DISPLAY_NAME, P.pkey,P.pname, GRP.ID FROM AO_8BA09E_GIT_REPOSITORY GRP
INNER JOIN AO_8BA09E_PROJECT_MAPPING PM
ON GRP.ID = PM.REPOSITORY_ID JOIN project P
ON PM.PROJECT_ID = P.ID
GROUP BY GRP.ROOT, GRP.DISPLAY_NAME,P.pkey,P.pname, GRP.ID
ORDER BY GRP.ID ASC;